#!/bin/bash
gbn=$(basename $BASH_SOURCE)
gdn=$(dirname $BASH_SOURCE)

if [ -z "$*" ]; then exit 1; fi

pkg=$1
pkg="${gdn}/../etc/packages/${pkg}"

if ! [ -r "${pkg}" ]; then exit 1; fi

pkg=$(cat "${pkg}" | grep -v -e "^#")

if [ -z "${pkg}" ]; then exit 1; fi

yum install $pkg
